build-and-test-ubuntu:
    image: registry.gitlab.com/ngless/ngless/ubuntu-ghc-stack:rolling
    stage: build

    before_script:
    - apt update
    - apt upgrade -y
    - stack upgrade
    - mkdir bin
    # Needed for tests that print UTF8 characters such as motus
    # Same issue as https://github.com/commercialhaskell/stack/issues/793

    variables:
        LC_ALL: "C.UTF-8"

    script:
    - STACKOPTS="--system-ghc" ./run-tests-static.sh
    - stack --local-bin-path bin install --system-ghc --ghc-options '-fPIC' --flag NGLess:embed

    artifacts:
        when: on_success
        paths:
        - bin/ngless
        - Modules/packages/
        expire_in: 1 month

build-and-test-alpine:
    image: registry.gitlab.com/ngless/ngless/alpine-ghc-stack:edge
    stage: build

    before_script:
    - apk update
    - apk upgrade
    - stack upgrade
    - mkdir bin

    script:
    - STACKOPTS="--system-ghc" ./run-tests-static.sh
    - stack --local-bin-path bin install --system-ghc --ghc-options '-fPIC' --flag NGLess:embed

    artifacts:
        when: on_success
        paths:
        - bin/ngless
        - Modules/packages/
        expire_in: 1 month
