sudo: false
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

language: python

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

env:
  - STACKOPTS=" --no-terminal"

python:
  - "2.7"

install: pip install tox

addons:
  apt:
    packages:
      - libgmp10
      - libgmp-dev
      - liblzma-dev
      - libcurl4-openssl-dev

script:
  - stack --no-terminal setup
  - make
  - ./run-tests.sh
